# Generated by Django 4.0.3 on 2022-04-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_auth_alter_blog_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='auth',
            new_name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='author_email',
            field=models.TextField(default='wsx2138@naver.com'),
        ),
    ]
