# Generated by Django 4.0.3 on 2022-04-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_auth_blog_author_blog_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_email',
            field=models.CharField(default='wsx2138@naver.com', max_length=50),
        ),
    ]
