# Generated by Django 4.0.3 on 2022-04-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
