# Generated by Django 4.0.3 on 2022-04-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank='True', null='True', upload_to='blog/'),
            preserve_default='True',
        ),
    ]
